package dev.agentconfig.workbench.scan;

public enum FindingCode {
    ROOT_NOT_DIRECTORY,
    ROOT_UNREADABLE,
    WALK_FAILED,
    SYMLINK_ESCAPE,
    SYMLINK_BROKEN,
    SYMLINK_CYCLE,
    SYMLINK_DIRECTORY_SKIPPED,
    SYMLINK_FILE_SKIPPED,
    UNSUPPORTED_SPECIAL_FILE,
    UNREADABLE_FILE,
    READ_FAILED,
    CONCURRENT_MODIFICATION,
    FILE_TOO_LARGE,
    DEPTH_LIMIT_REACHED,
    ENTRY_LIMIT_REACHED,
    TOTAL_BYTE_LIMIT_REACHED,
    SCAN_CANCELLED
}
